### ISSUE TITLE
Function countR is fucki*g my brain here

### ISSUE THREAD

**Issue by yoselibero** [raitocz/cecki#1]
I am using your library on many of my projects, but i love it!
Recently, i found usage of countR() to be defective for some cases:

**How to reproduce**
```
$string = new StringType('®');
echo $string->countR();
```

**Expected result:**
13

Got:
◕

I don't get it, is it stuck? I have no time for this fBS!

**What i tried**
- unplugging my headset
- setting date.sunset_zenith = 90.583333 in php.ini
- some stuff with untrim(), but i ended up with ◒

**Suggestion**
Removing circles around the characters like ® wouldn't lead to circle progress bar in a first place.

**Comment by raitocz** [comment]
This is first degree emergency right here. I'm glad you are using our CECKI even if it is not officially released yet, which might also lead to some [unforeseen consequences](https://combineoverwiki.net/wiki/Unforeseen_Consequences).

I will investigate and report but my guess here is that in it's complexity `countR()` function oversees the casual ® in favor of less frequent characters "r" and "R". We will try to cover this in our non-existent unit tests soon and run them few times if we can reproduce. This might take few months to analyse though.

**Comment by raitocz** [comment]
Fixed in PR https://github.com/raitocz/cecki/pull/2 which was merged
